export const achievements = [
  ["Minimal State","Complete the tutorial mission","19.0%"],
  ["Expendable Asset","Die on a mission","14.8%"],
  ["Body Count","Kill 100 enemies","10.8%"],
  ["Retail Investor","Complete 5 standard missions","10.2%"],
  ["And That's How It Started...","Sell ‘AnCom’s Secret Data’ to any faction","9.3%"],
  ["Pacifist","Clear a floor without firing a single shot","8.2%"],
  ["If It Bleeds...","Bleed to death","8.1%"],
  ["Active Trader","Complete 10 standard missions","6.7%"],
  ["I Have No Intention of Staying Here!","Carry out an emergency evacuation that causes the mission to fail","6.2%"],
  ["Expendables","Lose 5 clones","5.8%"],
  ["Courts under Ancap","Complete the mission ‘Taste of Revenge’","5.4%"],
  ["Task Failed Successfully","Win a mission after dying in the process","5.0%"],
  ["Hell is Only a Word. The Reality is Much, Much Worse.","Encounter a quasimorph Baron","4.4%"],
  ["The Spanish Inquisition","Kill a burning quasimorph","3.7%"],
  ["Prima Nocta","Die at the hands of a quasimorph Baron","3.1%"],
  ["Filed as Expenses","Lose 10 clones","3.0%"],
  ["I Don’t Want to Die in Canada","Hidden on Steam","3.0%"],
  ["BBQ","Cook meat over a truly open flame","2.0%"],
  ["C-beams Glitter in the Dark","Bring HIS Magnum to Saturn or one of its moons","1.8%"],
  ["Homo Famelicus","Die of starvation","1.8%"],
  ["Industrial Slaughter","Kill 1,000 enemies","1.8%"],
  ["By our Own Hands","Kill your first quasimorph Baron","1.7%"],
  ["Preferred Contractor","Reach maximum relations with one of the Hexarchs","1.7%"],
  ["Signed in Blood","Use a quasimorph pact","0.9%"],
  ["Need a Hand?","Complete a mission after an amputation","0.9%"],
  ["Cost of Business","Lose 25 clones","0.7%"],
  ["Hasta la vista, Baby","Shatter a frozen enemy into pieces","0.6%"],
  ["Like Flies to Honey","Hidden on Steam","0.5%"],
  ["Hold My Beer","Complete a mission after starting with no equipment at all","0.5%"],
  ["Alchemist","Perform a pact-upgrade ritual aboard HIS Magnum","0.4%"],
  ["That belongs in a Museum!","Deliver the Skull of Destiny to HIS Magnum","0.3%"],
  ["The Market Has Spoken","Kill the CEO of a minor corporation","0.3%"],
  ["First Amendment","Upgrade a quasimorph pact","0.3%"],
  ["Clone's Nightmare","Hidden on Steam","0.2%"],
  ["It's Alive!","Upgrade a single clone’s genome 10 times","0.2%"],
  ["Leviathan Falls","Complete the mission ‘The Glass Bead Game’","0.1%"],
  ["Leviathan Wakes","Complete the mission ‘God of Carnage’","0.1%"],
  ["Eternal Sunshine of the Spotless Mind","Let the Inner Rite complete the ritual in ‘Sonnenmensch’","0.1%"],
  ["Now, I am become Death","Kill the members of the Inner Rite in ‘Sonnenmensch’","0.1%"],
  ["The Burning Cradle","Complete the mission ‘The Hive Awakens’","0.1%"],
  ["Kiss of the Spider Woman","Complete the mission ‘Shattered Emerald’","0.1%"],
  ["Red Dawn","Complete the mission ‘Icepick’","0.1%"],
  ["As If Millions of Voices","Complete the mission ‘Sacred Flame’","0.1%"],
  ["Ménage à trois","Complete the mission ‘Eradication’","0.1%"],
  ["The Conqueror Worm","Complete the mission ‘Poison Trial’","0.1%"],
  ["Moves like Woody","Complete the mission ‘Ship of Ghouls’","0.1%"],
  ["Use Your Head","Hidden on Steam","0.1%"],
  ["Think About It","Hidden on Steam","0.1%"],
  ["Full Circle","In ‘Sonnenmensch,’ keep every Inner Rite member alive during the final assault","0.1%"],
  ["True Visage","Transform into a quasimorph Baron","0.1%"],
  ["The Return of Orpheus","Return from a dive into a bramfatura","0.1%"],
  ["Impossible Worlds","Travel to the pleroma using the telefaturic engine","0.1%"],
  ["A Complete Map of the Heavens","Visit every bramfatura","0.1%"],
  ["Wicked Souls","Reach the maximum curse level","0.1%"],
  ["Blue-Chip Operator","Complete 100 standard missions","0.1%"],
  ["Too Big to Fail","Complete 1,000 standard missions","0.1%"],
  ["Extermination Quota","Kill 10,000 enemies","0.1%"],
  ["Genocide Dividend","Kill 100,000 enemies","0.1%"],
  ["Moonshiner","Craft a Shavvashine","0.1%"],
  ["Final form","Build every upgrade for HIS Magnum","0.1%"],
  ["Personnel Depreciation","Lose 50 clones","0.1%"],
  ["Replaceable by Design","Lose 100 clones","0.1%"],
  ["Dog is Clone’s Best Friend","Hidden on Steam","0.1%"],
  ["Headcase","Survive the detonation of your own Cortex Bomb","0.1%"],
  ["666","Obtain the best possible quasimorph pact upgrade","0.1%"],
  ["New Deal","Create an alternative quasimorph pact","0.1%"],
  ["Henry Ford","Start all production lines","0.1%"],
  ["Fake News","Create 100 missions through the Monitoring Department","0.1%"],
  ["Stonks","Earn 50,000 Dignitas through barter","0.1%"],
  ["I Never Asked for This","Install implants in every body part","0.1%"],
  ["Ship of Theseus","Augment every body part","0.1%"],
  ["Bookworm","Fully develop the Scholar perk","0.1%"],
  ["Pimp My Gun","Upgrade weapons 20 times","0.1%"],
  ["Just a Flesh Wound","Complete a mission after losing three or more limbs","0.1%"],
  ["Cut Your Losses","Amputate an infected limb","0.1%"],
  ["Choose Life","Reach 100% in every addiction at the same time","0.1%"],
  ["Where We’re Going, We Won’t Need Eyes to See.","Evacuate while blind","0.1%"],
  ["Annihilation","Disintegrate an enemy without leaving a trace","0.1%"],
  ["Dead or Alive, You’re Coming with Me.","Dress the VIP in heavy armor","0.1%"],
  ["Hellraiser","Complete a mission after starting with the maximum curse level","0.1%"],
  ["Legend","See an ending on Unfair difficulty without a single death","0.1%"],
  ["We Need to Go Deeper","Reach the tenth floor of a bramfatura","0.1%"],
] as const;
